### ISSUE TITLE
Sortering af adressesøgning

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#40]
![SPS søgning](https://user-images.githubusercontent.com/10741426/193016679-ae6586d3-8d50-4ad6-9fd0-a4e63dd7e40f.png)

Vi undrer os over visningen af adresseforslag i søgninger. I det viste eksempel, hvor der er skrevet Høvedstensvej, foreslår nummer 1, 2 og 4, selv om der findes både 3A, 3B og 3C, som kommer før nr. 4. Det er ikke logisk for brugerne.

Vh Lars

**Comment by furesoe** [comment]
@klavspc Vi har også problemer med at Å bliver sorteret, som var det Aa og Æ, som var det Ae.
Kan der kigges på det også?

![image](https://user-images.githubusercontent.com/38730459/215755172-2558b1b1-b0ab-44c8-bc38-fb77d2eae577.png)

**Comment by furesoe** [comment]
@klavspc Og sortering på Lokalplaner giver heller ikke helt mening for mig...
Hvad sorteres listen efter? Og kan den sorteres efter plannr?

![image](https://user-images.githubusercontent.com/38730459/215766679-1402f7e0-ecf6-43e5-bacc-09e16c51eaa8.png)

**Comment by klavspc** [comment]
Note til mig selv
vedr. https://github.com/Septima/OneDoor/issues/40#issue-1390691818:
-  https://api.dataforsyningen.dk/adgangsadresser/autocomplete?q=h%C3%B8vedstensvej&type=adgangsadresse&side=1&per_side=9&noformat=1&srid=25832

vedr. https://github.com/Septima/OneDoor/issues/40#issuecomment-1410233430

- https://api.dataforsyningen.dk/vejstykker?q=a*&side=1&per_side=504&noformat=1
- https://api.dataforsyningen.dk/vejnavne?q=a*&side=1&per_side=504&noformat=1

**Comment by klavspc** [comment]
@Ellebjerg @furesoe 
Der er mange ting i dette issue - det gør det svært at svare og behandle enkeltvis. Dette burde rettelig være tre issues

mht denne: https://github.com/Septima/OneDoor/issues/40#issuecomment-1410233430:
Kan i ikke checke om det stadig forholder sig således? Jeg tror, at det er rettet i en senere version end den i har konstateret problemet i. Jeg har ihvertfald dette:
![image](https://user-images.githubusercontent.com/3736091/220417600-038cd95e-8844-4205-8ecb-83da43d209dd.png)

_Hvis_ det stadig forholder sig sådan så må i gerne sende mig version af OneDoor (s3), samt den del af konfigurationen, som vedrører dawaSearcher

**Comment by klavspc** [comment]
- [ ] [Husnummer-sortering](https://github.com/Septima/OneDoor/issues/40#issue-1390691818): Fikset i SS 5.55.13+
- [ ] [Vejsortering](https://github.com/Septima/OneDoor/issues/40#issuecomment-1410233430): Afventer [Spørgsmål](https://github.com/Septima/OneDoor/issues/40#issuecomment-1438856268)
- [ ] [Plansortering](https://github.com/Septima/OneDoor/issues/40#issuecomment-1410301862) Løses i [andet issue](https://github.com/Septima/OneDoor/issues/30#issuecomment-1438399400)

**Comment by klavspc** [comment]
Husnummersortering:
![image](https://user-images.githubusercontent.com/3736091/221586076-ebe557d1-5fe0-4cb9-92ec-4bd4c050f425.png)

**Comment by Ellebjerg** [comment]
Hej Klavs
Husnummersortering ser fint ud i den version, vi lige har fået installeret.
Vh Lars

**Comment by Ellebjerg** [comment]
Men vejsorteringen ser stadig sjov ud. Så vidt jeg kan se, skyldes det, at den ikke tager vejnavnene alfabetisk for hele navnet samlet men derimod for hvert ord i vejnavnet.
![image](https://user-images.githubusercontent.com/10741426/222143026-989a713f-14da-45b0-8311-b7955cd0fb4a.png)

**Comment by furesoe** [comment]
@klavspc 

Hvad er status på vejnavnesorteringen? Vi oplever jo samme problem som @Ellebjerg og Hvidovre.

**Comment by klavspc** [comment]
Vejnavne returneres i den rækkefølge som de modtages fra dawa

Den "blanke søgning" i har taget screenshot fra er i virkligheden en søgning på "a"

Her er det tilsvarende kald for _b_:

Kaldet til dawa: https://api.dataforsyningen.dk/vejnavne/autocomplete?q=b*&side=1&per_side=104&noformat=1&kommunekode=167

og som det bliver vist:
![image](https://github.com/Septima/OneDoor/assets/3736091/c9a61091-7b3e-49e7-8899-ade898d6cc25)


Jeg _vil_ kunne lave noget sortering i Septima Search, men det er ikke så trivielt som det kunne se ud
